# Generated by Django 5.0.4 on 2024-05-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/footballers'),
        ),
    ]
