# Generated by Django 5.0.4 on 2024-05-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0005_footballers_delete_footballer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballers',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
